a = [10, 20, (35,46,-45,"gsd",45.64),{24,63},{"saurabh":32, "shubham":35},"dhanesh"]
print(a)
# print(id(a))
# print(type(a))
# print(a[0])
# print(a[1])
# print(a[2][0:4:3])
# a[1]=-76
# print(a)
# print(id(a))
# print(type(a[2]))
# print(type(a[3]))
# print(type(a[4]))
# print(a.append(24),a)
# print(type(a[5]))
# print(id(a))
# print(id(a[0]))
# print(id(a[2]))
# print(id(a[3]))
# print(id(a[4]))
# print(id(a[5]))
# print(id(a[2][3]))
# print(id(a[5][1]))
# print(a[5][1:7:5])
# print(len(a[2]))
# print(len(a[3]))
# print(len(a[4]))
# print(len(a[5]))
# print(a.remove("dhanesh"), a)
#print(a.remove(10),a)
#b=a.replace("dhanesh","diganmbar")
#a[5]="diganmbar"
#print(a.remove(20),a)
del a[4]
print(a)
#print(a.clear(),a)...........
#print(a.clear(a[2:]),a)
#print(a.del(a[1]))
#print(a[4]["saurabh"]) 
