mystr = "harry is a good boy"
#print(mystr)
#print(len(mystr))
#print(mystr[6])
#print(mystr[0:6])
#print(mystr[0:76])
#print(mystr[0:6:2])
#print(mystr[0:])
#print(mystr[:6])
#print(mystr[:])
#print(mystr[0:17:2])
#print(mystr[:17:2])
#print(mystr[::2])
#print(mystr[::])
#print(mystr[::5678])
#print(mystr.endswith("boy"))
#print(mystr.count("o"))
#print(mystr.capitalize())
#print(mystr.find("is"))
#print(mystr.upper())
#print(mystr.lower=())
#print(mystr.replace("good","bad"))
#print(mystr.isalnum())
#print(mystr.isalpha())
#print(mystr[-1])
#print(mystr[-18:-5:2])
#print(mystr[-18:-5])
#print(mystr[-18:-5:])
#print(mystr[-18:])
#print(mystr[:-5])
#print(mystr[::2])
#print(mystr[-1:]+mystr[1:-1]+mystr[:1])
a = mystr[0]
b = mystr[-1]
print(mystr[-1]+mystr[1:18]+mystr[0])
